version: '3.6'

services:
  web:
    environment:
      - SIMPLETEST_BASE_URL=http://web/
      - SIMPLETEST_DB=mysql://db:db@db/db
      - BROWSERTEST_OUTPUT_DIRECTORY=
      - MINK_DRIVER_ARGS_WEBDRIVER=["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://chromedriver:9515"]
